// <auto-generated />
namespace PedidosWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class clped : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clped));
        
        string IMigrationMetadata.Id
        {
            get { return "201602152250332_clped"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
