//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Geral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Geral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PedidosWeb.Resources.Geral", typeof(Geral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante o processo. Contate o administrador. Erro: {0}.
        /// </summary>
        internal static string ContateAdminsitrador {
            get {
                return ResourceManager.GetString("ContateAdminsitrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item alterado com sucesso..
        /// </summary>
        internal static string ItemAlteradoSucesso {
            get {
                return ResourceManager.GetString("ItemAlteradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O item foi salvo com sucesso..
        /// </summary>
        internal static string ItemSalvoSucesso {
            get {
                return ResourceManager.GetString("ItemSalvoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro. Tente novamente mais tarde..
        /// </summary>
        internal static string TenteNovamente {
            get {
                return ResourceManager.GetString("TenteNovamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos..
        /// </summary>
        internal static string UsuarioSenhaInvalidos {
            get {
                return ResourceManager.GetString("UsuarioSenhaInvalidos", resourceCulture);
            }
        }
    }
}
